use_frameworks!

platform :ios, '10.0'

target 'APodDemo_Example' do
  pod 'APodDemo', :path => '../'

  target 'APodDemo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
